CREATE DATABASE DHT22Readings;

CREATE TABLE Reading (
    Id INT AUTO_INCREMENT NOT NULL,
	Datetime DATETIME NOT NULL,
	Temperature DECIMAL(5,2) NOT NULL,
	Humidity DECIMAL(5,2) NOT NULL,
	PRIMARY KEY (Id)
);
